### PR TITLE
Adding tests to Auth flow

### PR DESCRIPTION
**Pull request by girachawda**
- References: https://github.com/MusaAqeel/2107/issues/12

Adding additional testing to the auth flow

### CODE REVIEW

**Comment by MusaAqeel** [comment]
.

**Comment by MusaAqeel** [comment]
.

**Comment by MusaAqeel** [comment]
.

**Review by Toby-J-Carter — APPROVED** [review]
LGTM! (Paired on this together)

**Comment by MusaAqeel** [comment]
LGTM!

**Review by MusaAqeel — APPROVED** [review]

**Pull request merged**
