### PR TITLE
Frontend Pages

### PR DESCRIPTION
**Pull request by girachawda**
##Addresses
- Closes: https://github.com/MusaAqeel/2107-stealth/issues/4
- Closes: https://github.com/MusaAqeel/2107/issues/12
- Closes: https://github.com/MusaAqeel/2107/issues/11

Paired with @Toby-J-Carter 

Ran pnpm to install all jest software. View docs [here](https://nextjs.org/docs/app/building-your-application/testing/jest)

The FED Components built out are for the core chat functionality so that the user can type inside it and generate a list of songs

### CODE REVIEW

**Comment by MusaAqeel** [comment]
@girachawda resolve conflicts pls

**Comment by MusaAqeel** [comment]
@girachawda use tailwind, no css.

**Review by MusaAqeel — CHANGES_REQUESTED** [review]
CSS --> Tailwind
Remove LLM, thats not needed and you create that in an API route not a page

**Comment by girachawda** [comment]
> CSS --> Tailwind Remove LLM, thats not needed and you create that in an API route not a page

We will change from css to tailwind later as this is just core changes. The LLM Page is just a placeholder for testing the mocks, not actually a page we need. So I'll need to just keep it for now so that our tests run.

**Comment by MusaAqeel** [comment]
❌ **Branch name is invalid.**

Branch names should follow the format: `{user}/{branch_type}/{feature_name}`

- **User** must be one of: `maqeel`, `psilva`, `gchawda`, `tcarter`.
- **Branch type** must be one of: `dev`, `bug`, `fix`.
- **Feature name** is required and can be any valid string.

**Pull request merged**
