### PR TITLE
/protected -- /home + spotify song search + ai chat for songs

### PR DESCRIPTION
**Pull request by MusaAqeel**

### CODE REVIEW

**Comment by MusaAqeel** [comment]
✅ **Branch name is valid.**

**Comment by MusaAqeel** [comment]
✅ **Branch name is valid.**

**Comment by MusaAqeel** [comment]
✅ **Branch name is valid.**

**Review by patricksilva-yu — DISMISSED** [review]

**Review by girachawda — DISMISSED** [review]

**Comment by MusaAqeel** [comment]
✅ **Branch name is valid.**

**Pull request merged**
